---
title: "getCRUCLdata"
author: "Adam H. Sparks"
date: "2024-12-18"
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteEngine{knitr::rmarkdown_notangle}
  %\VignetteIndexEntry{getCRUCLdata}
  %\VignetteEncoding{UTF-8}
  %\VignetteDepends{terra}
  %\VignetteDepends{ggplot2}
  %\VignetteDepends{viridis}
  %\VignetteDepends{data.table}
---



## Introduction to _getCRUCLdata_

The _getCRUCLdata_ package provides functions that automate importing CRU CL v. 2.0 climatology data into R, facilitate the calculation of minimum temperature and maximum temperature, and formats the data into a [base::data.frame()] object or a [base::list()]
of [terra::rast()] objects.

CRU CL v. 2.0 data are a gridded climatology of 1961-1990 monthly means released in 2002 and cover all land areas (excluding Antarctica) at 10 arcminutes (0.1666667 arc degree) resolution.
For more information see the description of the data provided by the University of East Anglia Climate Research Unit (CRU), <https://crudata.uea.ac.uk/cru/data/hrg/tmc/readme.txt>.

## Changes to original CRU CL v. 2.0 data

This package automatically converts elevation values from kilometres to metres.

This package crops all spatial outputs to an extent of ymin = -60, ymax = 85, xmin = -180, xmax = 180. Note that the original wind data include land area for parts of Antarctica.

# Using _getCRUCLdata_

Logical arguments are used to specify the climatology elements to retrieve and parse.
All arguments default to `FALSE`.
The `create_CRU_*()` functions require an additional parameter, `dsn` to be provided that states where the files are locally stored.
The arguments for selecting the climatology elements for importing are:

- **pre** Logical. Fetch precipitation (millimetres/month) from server and return in the data?

- **pre_cv** Logical. Fetch cv of precipitation (percent) from server and return in the data?

- **rd0** Logical. Fetch wet-days (number days with >0.1 millimetres rain per month) and return in the data?

- **dtr** Logical. Fetch mean diurnal temperature range (degrees Celsius) and return it in the data?

- **tmp** Logical. Fetch temperature (degrees Celsius) and return it in the data?

- **tmn** Logical. Calculate minimum temperature values (degrees Celsius) and return it in the data?

- **tmx** Logical. Calculate maximum temperature (degrees Celsius) and return it in the data?

- **reh** Logical. Fetch relative humidity and return it in the data?

- **sunp** Logical. Fetch sunshine, percent of maximum possible (percent of day length) and return it in data?

- **frs** Logical. Fetch ground-frost records (number of days with ground-frost per month) and return it in data?

- **wnd** Logical. Fetch 10m wind speed (metres/second) and return it in the data?

- **elv** Logical. Fetch elevation (and convert to metres from kilometres) and return it in the data?

- **dsn** *For `create_CRU_stack()`* and *`create_CRU_df()`* only.
Local file path where CRU CL v. 2.0 .dat.gz files are located.

### Creating data frames for use in R

The `get_CRU_df()` function automates the download process and creates data frames of the climatology elements.


``` r
library(getCRUCLdata)
#> Error in library(getCRUCLdata): there is no package called 'getCRUCLdata'

CRU_data <- get_CRU_df(pre = TRUE,
                       pre_cv = TRUE,
                       rd0 = TRUE,
                       tmp = TRUE,
                       dtr = TRUE,
                       reh = TRUE,
                       tmn = TRUE,
                       tmx = TRUE,
                       sunp = TRUE,
                       frs = TRUE,
                       wnd = TRUE,
                       elv = TRUE)
#> Error in get_CRU_df(pre = TRUE, pre_cv = TRUE, rd0 = TRUE, tmp = TRUE, : could not find function "get_CRU_df"

CRU_data
#> Error: object 'CRU_data' not found
```

Perhaps you only need one or two elements, it is easy to create a data frame of mean temperature only.


``` r
t <- get_CRU_df(tmp = TRUE)
#> Error in get_CRU_df(tmp = TRUE): could not find function "get_CRU_df"

t
#> function (x) 
#> UseMethod("t")
#> <bytecode: 0x10d54ee30>
#> <environment: namespace:base>
```

#### Plotting data from the data frame

Now that we have the data, we can plot it easily using _ggplot2_ and the _viridis_ package for the colour scale.


``` r
library(ggplot2)
library(viridis)

ggplot(data = t, aes(x = lon, y = lat, fill = tmp)) +
  geom_tile() +
  scale_fill_viridis(option = "inferno") +
  coord_quickmap() +
  ggtitle("Global Mean Monthly Temperatures 1961-1990") +
  facet_wrap( ~ month, nrow = 4)
#> Error in `ggplot()`:
#> ! `data` cannot be a function.
#> ℹ Have you misspelled the `data` argument in `ggplot()`
```

We can also generate a violin plot of the same data to visualise how the temperatures change throughout the year.


``` r
ggplot(data = t, aes(x = month, y = tmp)) +
  geom_violin() +
  ylab("Temperature (˚C)") +
  labs(title = "Global Monthly Mean Land Surface Temperatures From 1960-1991",
       subtitle = "Excludes Antarctica")
#> Error in `ggplot()`:
#> ! `data` cannot be a function.
#> ℹ Have you misspelled the `data` argument in `ggplot()`
```

#### Saving the `data.frame` as a CSV (comma separated values file) locally

Save the resulting `data.frame` to local disk as a comma separated (CSV)
file to local disk, using _data.table_'s `fwrite()`.


``` r
library(data.table)
fwrite(x = t, file = "~/CRU_tmp.csv")
```

### Creating terra raster stacks for use in R and saving for use in another GIS

For working with spatial data, _getCRUCLdata_ provides a function that create lists of _terra_ stacks of the data.

The `get_CRU_stack()` functions provide similar functionality to `get_CRU_df()`, but rather than returning a data frame, it returns a list of `terra::rast()` objects for use in an R session.

The `get_CRU_stack()` function automates the download process and creates a `terra::rast()` object of the CRU CL v. 2.0 climatology elements.
Illustrated here is creating a `terra::rast()` of all CRU CL v. 2.0 climatology elements available.


``` r
CRU_stack <- get_CRU_stack(
  pre = TRUE,
  pre_cv = TRUE,
  rd0 = TRUE,
  tmp = TRUE,
  dtr = TRUE,
  reh = TRUE,
  tmn = TRUE,
  tmx = TRUE,
  sunp = TRUE,
  frs = TRUE,
  wnd = TRUE,
  elv = TRUE
)
#> Error in get_CRU_stack(pre = TRUE, pre_cv = TRUE, rd0 = TRUE, tmp = TRUE, : could not find function "get_CRU_stack"

CRU_stack
#> Error: object 'CRU_stack' not found
```

The `create_CRU_stack()` function works in the same way with only one minor difference.
You must supply the location of the files on the local disk (`dsn`) that you wish to import.


``` r
t <- create_CRU_stack(tmp = TRUE, dsn = "~/Downloads")
```

#### Plotting terra rast objects of tmin and tmax

Because the stacks are in a `list()`, we need to access each element of the list individually to plot them, that's what the `[[1]]` or `[[2]]` is, the first or second element of the list.
Here using `[[7]]` we will plot the monthly average minimum temperature for all twelve months.


``` r
library(terra)

plot(CRU_stack[[7]])
```

To plot only one month from the stack is also possible. Here we plot maximum temperature for July.
Note that we use indexing `[[2]]` as before but append a `$jul` to the object.
This is the name of the layer in the `terra::rast()`.
So, we are telling R to plot the second object in the `CRU_stack` list, which is `tmx` and from that terra rast, plot only the layer for July.


``` r
plot(t[[8]]$jul)
```

#### Saving terra objects to local disk

The [terra::rast()] objects can be saved to disk as geotiff files (others are available, see help for `terra::writeRaster()` for more options) on the `Data` directory with a tmn or tmx prefix to the month for a file name.


``` r
library(terra)

dir.create(file.path("~/Data"), showWarnings = FALSE)
writeRaster(
  t$tmn,
  filename = file.path("~/Data/tmn_", names(t$tmn)),
  bylayer = TRUE,
  format = "GTiff"
)

writeRaster(
  t$tmx,
  filename = file.path("~/Data/tmx_", names(t$tmn)),
  bylayer = TRUE,
  format = "GTiff"
)
```

# CRU CL v. 2.0 reference and abstract

Mark New (1,*), David Lister (2), Mike Hulme (3), Ian Makin (4)
A high-resolution data set of surface climate over global land areas Climate Research, 2000, Vol 21, pg 1-25
(1) School of Geography and the Environment, University of Oxford,
    Mansfield Road, Oxford OX1 3TB, United Kingdom
(2) Climatic Research Unit, and (3) Tyndall Centre for Climate Change Research,
    both at School of Environmental Sciences, University of East Anglia,
    Norwich NR4 7TJ, United Kingdom
(4) International Water Management Institute, PO Box 2075, Colombo, Sri Lanka

**ABSTRACT:** We describe the construction of a 10-minute latitude/longitude
data set of mean monthly surface climate over global land areas, excluding
Antarctica. The climatology includes 8 climate elements - precipitation, wet-day
frequency, temperature, diurnal temperature range, relative humidity,sunshine
duration, ground frost frequency and windspeed - and was interpolated from a
data set of station means for the period centred on 1961 to 1990. Precipitation
was first defined in terms of the parameters of the Gamma distribution, enabling
the calculation of monthly precipitation at any given return period. The data
are compared to an earlier data set at 0.5 degrees latitude/longitude resolution
and show added value over most regions. The data will have many applications in
applied climatology, biogeochemical modelling, hydrology and agricultural
meteorology and are available through the School of Geography Oxford
(https://www.geog.ox.ac.uk), the International Water Management Institute
"World Water and Climate Atlas" (https://www.iwmi.org/) and the Climatic
Research Unit (https://www.uea.ac.uk/groups-and-centres/climatic-research-unit).
