#' @title Create a List of Raster Stack Objects From CRU CL2.0 Climatology Variables on Local Disk
#'
#'@description This function automates importing CRU CL2.0 climatology data into
#'R from locally available data files and creates a list of raster stacks of the
#'data.  If requested, minimum and maximum temperature may also be automatically
#'calculated as described in the data readme.txt file.
#'
#'Nomenclature and units from readme.txt:
#'\describe{
#'\item{pre}{precipitation (millimetres/month)}
#'  \describe{
#'    \item{cv}{cv of precipitation (percent)}
#'  }
#'\item{rd0}{wet-days (number days with >0.1mm rain per month)}
#'\item{tmp}{mean temperature (degrees Celsius)}
#'\item{dtr}{mean diurnal temperature range (degrees Celsius)}
#'\item{reh}{relative humidity (percent)}
#'\item{sunp}{sunshine (percent of maximum possible (percent of day length))}
#'\item{frs}{ground-frost (number of days with ground-frost per month)}
#'\item{wnd}{10 metre windspeed (metres/second)}
#'\item{elv}{elevation (automatically converted to metres)}
#'}
#'For more information see the description of the data provided by CRU,
#'\url{https://crudata.uea.ac.uk/cru/data/hrg/tmc/readme.txt}
#'
#' @details This function generates a raster stack object in R from local files
#' already downloaded via a web browser or FTP. The user will need to specify
#' the following options.
#' @param pre_cv Logical. Create a raster stack of precipitation CV? Requires
#' precipitation file to be available. Defaults to FALSE.
#' @param tmn Logical. Calculate minimum temperature values (degrees Celsius)
#' and return it in a raster stack? Requires tmp and dtr files to both be
#' available for calculation. Defaults to FALSE.
#' @param tmx Logical. Calculate maximum temperature (degrees Celsius) and
#' return it in a raster stack?  Requires tmp and dtr files to both be
#' available for calculation. Defaults to FALSE.
#' @param tmp Logical. When calculating tmn and/or tmx, keep tmp? Defaults to
#' FALSE.
#' @param dtr Logical. When calculating tmn and/or tmx, keep tmp? Defaults to
#' FALSE.
#' @param dsn Required. Local file path where CRU CL2.0 .dat.gz files are
#' located.
#'
#' @examples
#' # Create a raster stack of precipitation and temperature from pre and tmp
#' # files in the Downloads directory.
#' \dontrun{
#' CRU_pre_tmp <- create_CRU_stack(pre = TRUE, tmp = TRUE, dsn = "~/Downloads")
#'}
#' @seealso
#' \code{link{get_CRU_stack}}
#'
#' @note
#' This package automatically converts elevation values from kilometres to
#' metres.
#'
#' This package crops all spatial outputs to an extent of ymin = -60, ymax = 85,
#' xmin = -180, xmax = 180. Note that the original wind data include land area
#' for parts of Antarctica, these data are excluded in the raster stacks
#' generated by this function.

#'
#' @export
create_CRU_stack <-
  function(pre_cv = FALSE,
           tmn = FALSE,
           tmx = FALSE,
           dtr = FALSE,
           tmp = FALSE,
           dsn = NULL) {

    .validate_dsn(dsn)

    files <-
      list.files(dsn, pattern = ".dat.gz$", full.names = TRUE)

    s <- create_stacks(pre_cv, tmn, tmx, files)
    return(s)
}

