#' Download and create a list of terra rast objects of climatology parameters
#'
#' This function automates downloading and importing CRU CL v. 2.0
#' climatology data into \R and creates a list of [terra()]
#' [terra::rast()] of the data.  If requested, minimum and maximum
#' temperature may also be automatically calculated as described in the data
#' readme.txt file.  Data may be cached for later use by this function, saving
#' time downloading files in future use of the function.
#'
#' @inheritSection get_CRU_df Nomenclature and Units
#' @inheritParams get_CRU_df
#' @examplesIf interactive()
#'
#' # Download data and create a [terra()] [terra::rast()]
#' # object of precipitation and temperature without caching the data files
#' CRU_pre_tmp <- get_CRU_stack(pre = TRUE, tmp = TRUE)
#'
#' CRU_pre_tmp
#'
#'
#' @seealso
#' [create_CRU_stack()]
#' [manage_cache()]
#'
#' @return A [base::list()] of \CRANpkg{terra} [terra::rast()] objects of CRU CL
#'  v. 2.0 climatology elements
#'
#' @author Adam H. Sparks, \email{adamhsparks@@gmail.com}
#'
#' @note
#' This package automatically converts elevation values from kilometres to
#' metres.
#'
#' This package crops all spatial outputs to an extent of ymin = -60, ymax = 85,
#' xmin = -180, xmax = 180.  Note that the original wind data include land area
#' for parts of Antarctica, these data are excluded in the terra rast objects
#' generated by this function.
#'
#' @export get_CRU_stack

get_CRU_stack <-
  function(pre = FALSE,
           pre_cv = FALSE,
           rd0 = FALSE,
           tmp = FALSE,
           dtr = FALSE,
           reh = FALSE,
           tmn = FALSE,
           tmx = FALSE,
           sunp = FALSE,
           frs = FALSE,
           wnd = FALSE,
           elv = FALSE,
           cache = FALSE) {
    .check_vars_FALSE(
      pre,
      pre_cv,
      rd0,
      tmp,
      dtr,
      reh,
      tmn,
      tmx,
      sunp,
      frs,
      wnd,
      elv
    )

    cache_dir <- .set_cache(cache)

    files <- .get_CRU(
      pre,
      pre_cv,
      rd0,
      tmp,
      dtr,
      reh,
      tmn,
      tmx,
      sunp,
      frs,
      wnd,
      elv,
      cache_dir
    )

    if (pre_cv) {
      pre <- TRUE
    }

    return(.create_stacks(tmn, tmx, tmp, dtr, pre, pre_cv, files))
  }
