# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "month", # <.create_dt>
  "pre_cv", # <.read_local_files>
  "i.pre_cv", # <.read_local_files>
  "elv", # <.read_local_files>
  NULL
))
